# Generated by Django 4.2.11 on 2024-09-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminapps',
            name='app_image',
        ),
    ]
