# Generated by Django 4.2.11 on 2024-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_adminapps_app_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapps',
            name='app_points',
            field=models.IntegerField(default=100),
        ),
    ]
