# Generated by Django 4.2.11 on 2024-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_adminapps_app_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('app_link', models.URLField()),
                ('app_screenshot', models.ImageField(upload_to='')),
            ],
        ),
    ]
