# Generated by Django 4.2.11 on 2024-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userapps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapps',
            name='app_screenshot',
            field=models.ImageField(upload_to='app_screenshots'),
        ),
    ]
