# Generated by Django 4.2.11 on 2024-09-18 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_userapps_app_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapps',
            name='admin_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.adminapps'),
        ),
        migrations.AddField(
            model_name='userapps',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
